name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/backend.yml"
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      NODE_ENV: production
    steps:
      - name: Pull latest code
        run: |
          cd /home/sushant/app/prod/MyDrive
          git pull origin main

      - name: Setup env
        run: |
          cd /home/sushant/app/prod/MyDrive/server

      - name: Install & restart
        run: |
          cd /home/sushant/app/prod/MyDrive/server
          npm install
          pm2 restart backend-8080 --update-env