name: Deploy Dev Backend

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/dev-backend.yml"
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - name: Pull latest code
        run: |
          cd /home/sushant/MyDrive
          git pull origin dev

      - name: Setup env
        run: |
          cd /home/sushant/MyDrive/server

      - name: Install & restart
        run: |
          cd /home/sushant/MyDrive/server
          npm install
          pm2 startOrReload ecosystem.config.cjs --update-env