name: Deploy Dev Backend

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/dev-backend.yml"
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      NODE_ENV: development
    steps:
      - name: Pull latest code
        run: |
          cd /home/sushant/app/dev/MyDrive
          git pull origin dev

      - name: Install & restart
        run: |
          cd /home/sushant/app/dev/MyDrive/server
          npm install
          pm2 restart dev-backend-8001 --update-env