name: Deploy Dev Frontend

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/dev-frontend.yml"
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
    steps:
      - name: Pull latest code
        run: |
          cd /home/sushant/MyDrive
          git pull origin dev

      - name: Setup env
        run: |
          cd /home/sushant/MyDrive/client
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env

      - name: Install & restart
        run: |
          cd /home/sushant/MyDrive/client
          npm install
          npm run build
          pm2 restart dev-frontend-3001 --update-env