name: Deploy Frontend

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
    steps:
      - name: Pull latest code
        run: |
          cd /home/sushant/MyDrive
          git pull origin main

      - name: Setup env
        run: |
          cd /home/sushant/MyDrive/client
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env

      - name: Install & restart
        run: |
          cd /home/sushant/MyDrive/client
          npm install
          npm run build
          pm2 restart frontend-3000 --update-env